name: Publish Package to npm

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.20

      - name: Install dependencies
        run: bun install

      - name: Run typechecks
        run: bun run typecheck

      - name: Update package.json with release tag
        run: |
          echo "Updating package.json version to ${{ github.event.release.tag_name }}"
          bun ./scripts/version.ts "${{ github.event.release.tag_name }}"

      - name: Commit and push version update
        run: |
          TAG="${{ github.event.release.tag_name }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "release: $TAG [skip ci]"
          git push origin ${{ github.event.repository.default_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        run: bun publish --access public --auth-type legacy
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
